-- Crear la base de datos
CREATE DATABASE SUPERFRESH;
USE SUPERFRESH;

-- Tabla Persona
CREATE TABLE persona (
    ID_PERSONA INT PRIMARY KEY AUTO_INCREMENT,
    DISTRITO VARCHAR(30),
    APELLIDO_PATERNO VARCHAR(50),
    APELLIDO_MATERNO VARCHAR(50),
    NOMBRE VARCHAR(50),
    DNI CHAR(8),
    CARNET_EXTRANJERO VARCHAR(30),
    ESTADO_CIVIL CHAR(2),
    FECHA_NACIMIENTO DATE,
    DIRECCION VARCHAR(100),
    CELULAR VARCHAR(9),
    EMAIL VARCHAR(100),
    USUCRE VARCHAR(50),
    FECCRE DATETIME,
    PCCRE VARCHAR(50),
    USUMOD VARCHAR(50),
    FECMOD DATETIME,
    PCMOD VARCHAR(50),
    ESTADO CHAR(1)
);

-- Tabla Empresa
CREATE TABLE empresa (
    id_empresa INT PRIMARY KEY AUTO_INCREMENT,
    razon_social VARCHAR(150) NOT NULL,
    nombre_comercial VARCHAR(150),
    ruc CHAR(11) NOT NULL UNIQUE,
    direccion VARCHAR(200),
    telefono CHAR(9),
    correo_electronico VARCHAR(100),
    USUCRE VARCHAR(50),
    FECCRE DATETIME,
    PCCRE VARCHAR(50),
    USUMOD VARCHAR(50),
    FECMOD DATETIME,
    PCMOD VARCHAR(50),
    ESTADO CHAR(1)
);

-- Tabla Empleado (simplificada)
CREATE TABLE Empleado (
    ID_EMPLEADO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PERSONA INT,
    CARGO VARCHAR(100),  -- Campo único para el cargo
    USUCRE VARCHAR(50),
    FECCRE DATETIME,
    PCCRE VARCHAR(50),
    USUMOD VARCHAR(50),
    FECMOD DATETIME,
    PCMOD VARCHAR(50),
    ESTADO CHAR(1),
    FOREIGN KEY (ID_PERSONA) REFERENCES Persona(ID_PERSONA)
);

-- Tabla Perfil
CREATE TABLE perfil (
    ID_PERFIL INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_PERFIL VARCHAR(100),
    USUCRE VARCHAR(50),
    FECCRE DATETIME,
    PCCRE VARCHAR(50),
    USUMOD VARCHAR(50),
    FECMOD DATETIME,
    PCMOD VARCHAR(50),
    ESTADO CHAR(1)
);

-- Tabla Usuario
CREATE TABLE usuario (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PERSONA INT,
    LOGEO VARCHAR(100),
    CLAVE VARCHAR(100),
    USUCRE VARCHAR(50),
    FECCRE DATETIME,
    PCCRE VARCHAR(50),
    USUMOD VARCHAR(50),
    FECMOD DATETIME,
    PCMOD VARCHAR(50),
    ESTADO CHAR(1),
    FOREIGN KEY (ID_PERSONA) REFERENCES Persona(ID_PERSONA)
);

-- Tabla Perfil Usuario
CREATE TABLE perfil_usuario (
    ID_PERFIL_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PERFIL INT,
    ID_USUARIO INT,
    USUCRE VARCHAR(50),
    FECCRE DATETIME,
    PCCRE VARCHAR(50),
    USUMOD VARCHAR(50),
    FECMOD DATETIME,
    PCMOD VARCHAR(50),
    FOREIGN KEY (ID_PERFIL) REFERENCES perfil(ID_PERFIL),
    FOREIGN KEY (ID_USUARIO) REFERENCES usuario(ID_USUARIO)
);

-- Tabla Menu
CREATE TABLE menu (
    ID_MENU INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_MENU VARCHAR(100),
    USUCRE VARCHAR(50),
    FECCRE DATETIME,
    PCCRE VARCHAR(50),
    USUMOD VARCHAR(50),
    FECMOD DATETIME,
    PCMOD VARCHAR(50)
);

-- Tabla Submenu
CREATE TABLE submenu (
    ID_SUBMENU INT PRIMARY KEY AUTO_INCREMENT,
    ID_MENU INT,
    NOMBRE_SUBMENU VARCHAR(100),
    NOMBRE_FORMULARIO VARCHAR(100),
    USUCRE VARCHAR(50),
    FECCRE DATETIME,
    PCCRE VARCHAR(50),
    USUMOD VARCHAR(50),
    FECMOD DATETIME,
    PCMOD VARCHAR(50),
    FOREIGN KEY (ID_MENU) REFERENCES menu(ID_MENU)
);

-- Tabla Detalle Permiso
CREATE TABLE detalle_permiso (
    ID_DETALLE_PERMISO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PERFIL INT,
    ID_SUBMENU INT,
    ACCESO CHAR(1),
    USUCRE VARCHAR(50),
    FECCRE DATETIME,
    PCCRE VARCHAR(50),
    USUMOD VARCHAR(50),
    FECMOD DATETIME,
    PCMOD VARCHAR(50),
    FOREIGN KEY (ID_PERFIL) REFERENCES perfil(ID_PERFIL),
    FOREIGN KEY (ID_SUBMENU) REFERENCES submenu(ID_SUBMENU)
);

-- Tabla Control de Pedidos
CREATE TABLE control_pedidos (
    ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    Pedido VARCHAR(20) NOT NULL,
    Razon_social VARCHAR(150) NOT NULL,
    RUC CHAR(11) NOT NULL,
    Direccion VARCHAR(200),
    Referencia VARCHAR(100),
    Contacto VARCHAR(100),
    Telefono CHAR(9),
    Condicion_pago VARCHAR(30),
    Precio_3kg_SF DECIMAL(10,2),
    Precio_C_C DECIMAL(10,2),
    Precio_1_5kg DECIMAL(10,2),
    Tipo_documento ENUM('Factura', 'Boleta'),
    Cantidad_3kg INT,
    Cantidad_C_C INT,
    Cantidad_1_5kg INT,
    Cambio_3kg INT,
    Cambio_C_C INT,
    Cambio_1_5kg INT,
    Precio_facturar DECIMAL(10,2),
    Valor_venta DECIMAL(10,2),
    IGV_18 DECIMAL(10,2),
    USUCRE VARCHAR(50),
    FECCRE DATETIME,
    PCCRE VARCHAR(50),
    USUMOD VARCHAR(50),
    FECMOD DATETIME,
    PCMOD VARCHAR(50),
    Estado CHAR(1)
);

-- Tabla Resumen Clientes
CREATE TABLE resumen_clientes (
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    Numero INT NOT NULL,
    Razon_social VARCHAR(150) NOT NULL,
    RUC CHAR(11) NOT NULL,
    Direccion VARCHAR(200),
    Referencia VARCHAR(100),
    Contacto VARCHAR(100),
    Telefono CHAR(9),
    Condicion VARCHAR(30),
    Precio_3kg_SF DECIMAL(10,2),
    Precio_C_C DECIMAL(10,2),
    Precio_1_5kg DECIMAL(10,2),
    USUCRE VARCHAR(50),
    FECCRE DATETIME,
    PCCRE VARCHAR(50),
    USUMOD VARCHAR(50),
    FECMOD DATETIME,
    PCMOD VARCHAR(50),
    Estado CHAR(1)
);

-- Tabla Control de Despacho
CREATE TABLE control_despacho (
    ID_DESPACHO INT PRIMARY KEY AUTO_INCREMENT,
    Tipo VARCHAR(50),
    Fecha DATE,
    Cantidad INT,
    Envase VARCHAR(50),
    Lote_envase VARCHAR(50),
    Presentacion VARCHAR(50),
    Lote_producto VARCHAR(50),
    Fecha_vencimiento DATE,
    Cliente VARCHAR(150),
    Observaciones TEXT,
    USUCRE VARCHAR(50),
    FECCRE DATETIME,
    PCCRE VARCHAR(50),
    USUMOD VARCHAR(50),
    FECMOD DATETIME,
    PCMOD VARCHAR(50),
    Estado CHAR(1)
);

-- Nueva Tabla: Ingreso a Almacén de Producto Terminado (Formato 35 - Producción)
CREATE TABLE ingreso_almacen_producto (
    ID_INGRESO INT PRIMARY KEY AUTO_INCREMENT,
    HORA TIME,
    CANTIDAD INT,
    ENVASE VARCHAR(50),
    LOTE_ENVASE VARCHAR(50),
    PRESENTACION VARCHAR(50),
    LOTE_PRODUCTO VARCHAR(50),
    FECHA_VENCIMIENTO DATE,
    USUCRE VARCHAR(50),
    FECCRE DATETIME,
    PCCRE VARCHAR(50),
    USUMOD VARCHAR(50),
    FECMOD DATETIME,
    PCMOD VARCHAR(50),
    ESTADO CHAR(1)
);